### ISSUE TITLE
Pre Receive Hook behavior on Jira Create Branch

### ISSUE THREAD

**Issue by aronfe** [reconquest/atlassian-external-hooks#92] opened 2019-07-10 14:43 UTC
Suspecting different behavior using Pre Receive Hook add-on in Bitbucket version 4.02 vs. Bitbucket version 6.4.0

When we are creating a branch in Jira 7.13.4 it does NOT trigger the Pre Receive Hook in Bitbucket 4.02, however when we are creating the branch in Jira 7.13.4 it DOES trigger the Pre Receive Hook in Bitbucket 6.4.0

Could this be correct?

**Comment by kovetskiy** [comment] 2019-07-10 14:51
Hi, yes, that's correct. 

Here is the list of events that will trigger Pre Receive Hook:
https://github.com/reconquest/atlassian-external-hooks/blob/465c5dd51551b8ccea5ca9da630fb477c529e3b0/src/main/java/com/ngs/stash/externalhooks/hook/ExternalPreReceiveHook.java#L54-L60

We can expose this list of triggers and make them configurable if the current behavior disrupts your workflow.

Thank you for the report.

**Comment by ericfru** [comment] 2019-07-10 16:01
Hi There,

Thank you for that information. Just for potential other issues we may come across, are you able to provide us with a list of the  major changes done between these versions? (I know it's a lot I'm sure as we're making a big jump).

Thank you,

**Comment by seletskiy** [comment] 2019-07-11 22:15
Adding to the fact that Pre- and Post- hooks are now triggered on Tag/Branch Creation/Deletion most important changes outlined before.

Following environment variables are now marked as deprecated and their alternatives should be considered to be used instead. No immediate change required.
```
    STASH_USER_NAME → BB_USER_DISPLAY_NAME
    STASH_USER_NAME → BB_USER_DISPLAY_NAME
    STASH_USER_EMAIL → BB_USER_EMAIL
    STASH_REPO_NAME → BB_REPO_SLUG
    STASH_REPO_IS_FORK → BB_REPO_IS_FORK
    STASH_PROJECT_KEY → BB_PROJECT_KEY
    STASH_BASE_URL → BB_BASE_URL
    STASH_REPO_CLONE_SSH → BB_REPO_CLONE_SSH
    STASH_REPO_CLONE_HTTP → BB_REPO_CLONE_HTTP 
```
Following environment variables were removed without replacement due limitations in Bitbucket Server starting from 6.2.0.
```
    STASH_PROJECT_NAME
    STASH_IS_DIRECT_WRITE
    STASH_IS_DIRECT_ADMIN 
```
Merge Check will no longer add comments to Pull Requests or automatically reject them and no such configuration is possible.

Pre- and Post-Receive Hooks will now always pass theirs' output to user no matter which exit code was returned from script.

**Comment by justin-rush** [comment] 2019-11-13 21:36
Support Entitlement Number: SEN-15105760

We are not able to upgrade our version of BitBucket due to

 triggers.add(StandardRepositoryHookTrigger.TAG_DELETE); 
 triggers.add(StandardRepositoryHookTrigger.TAG_CREATE); 
 triggers.add(StandardRepositoryHookTrigger.BRANCH_DELETE); 
 triggers.add(StandardRepositoryHookTrigger.BRANCH_CREATE); 

Our internal build processes and user workflow will not work with these triggers calling our pre-receive script. Can you make them configurable as commented on July 10th?

**Comment by seletskiy** [comment] 2019-11-13 22:39
@justin-rush: Hello.

We're on it.
To implement it best usability-wise it will be very helpful for us if you could answer on the following questions:

1. Do you have External Hooks configured on project-level or repository-level?
2. How much projects/repositories you have External Hooks configured for?

**Comment by justin-rush** [comment] 2019-11-14 16:43
Thank you for your assistance.
1. We have External Hooks configured solely at the repository level.
2. We have External Hooks configured for approximately 200 repositories.

**Comment by seletskiy** [comment] 2019-11-14 20:59
@justin-rush: Thanks!

We're going to implement global plugin configuration page where tag/branch triggers can be disabled. Will post update here as soon as new version will be available via Atlassian Marketplace.

In meantime we can issue a workaround release with triggers in question disabled, so let me know if it's critical and you need it ASAP.

**Comment by justin-rush** [comment] 2019-11-14 22:02
Excellent, we can wait for it to propagate through the Atlassian Marketplace. Just keep me posted when it is available. Thanks again.

**Comment by kovetskiy** [comment] 2019-11-25 11:44
@justin-rush Hi! Just letting you know that we've finished the development stage of the settings page and have moved the task to our QA. We're planning to release it this week.

Here is demo gif:
![external-hooks settings](https://user-images.githubusercontent.com/8445924/69537780-dff0db80-0f91-11ea-91e7-d7d3dfccfce0.gif)

**Comment by kovetskiy** [comment] 2019-11-29 12:41
@justin-rush we've released the feature, please check v9.0.0, you can install it via official marketplace or via 'Manage Apps' page in the admin panel.

https://marketplace.atlassian.com/apps/1211631/external-hooks-by-reconquest/version-history#b6452

Docs: https://external-hooks.reconquest.io/docs/triggers/

Please close the issue if the issue is resolved for you.

**Comment by kovetskiy** [comment] 2019-12-05 10:43
@justin-rush Hi! Have you had a chance to check the new feature? Is the issue resolved for you?

**Comment by justin-rush** [comment] 2019-12-06 15:27
Sorry for the delay, my team tested your new feature extensively in our sandbox environment and your change meets our needs. Thank you for your timely feature work.

**Comment by kovetskiy** [comment] 2019-12-06 17:15
Thank you for letting us know! Feel free to re-open the issue in any case.

**Closed by kovetskiy** 2019-12-06 17:15 UTC
Labels: feature-request, need-feedback, question
